# Disable OS Banner (before login)
DebianBanner no

# Add an additional port
Port 22
Port 22022

AddressFamily inet
ListenAddress 0.0.0.0

# Disable root login entirely
PermitRootLogin no

# Disable password authentication 
PasswordAuthentication no

# Disable empty passwords
PermitEmptyPasswords no

# Disable keyboard-interactive and challenge-response auth (s/key or PAM-based prompts)
ChallengeResponseAuthentication no

# Disable Pluggable Authentication Module (PAM)
#UsePAM no
## UsePAM can ensure locked account cannot login

# Use key-based authentication
PubkeyAuthentication yes

# Use only SSH protocol 2
Protocol 2

# Limit authentication attempts per connection
MaxAuthTries 3

# Set connection timeout 
ClientAliveInterval 600
ClientAliveCountMax 2

# Disable X11 forwarding (not needed)
X11Forwarding no

# Disable TCP forwarding unless you specifically need it
#AllowTcpForwarding no
AllowTcpForwarding local


# Only allow specific users to connect via SSH
AllowUsers xx ubuntu opc

# Use strong key exchange algorithms, ciphers, and MACs
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Max login time (in seconds) after connecting - prevent rbute-force or DoS
LoginGraceTime 20

# Limit the open multiplexed shell login sessions per network (default 10)
MaxSessions 3

# To print the Message of the Dar upon successful login
PrintMotd yes

# Disable custom environment variables from client
PermitUserEnvironment no


